### ISSUE TITLE
Milestone 1 draft complete

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/DSCI_522_GROUP3_COFFEERATINGS#13]
Hello Team

All the sections for Milestone 1 are now complete and uploaded to the repo. Please have a look and feel free to suggest any changes/updates. Myself and Arlin have done a review of Grammar/ Spelling and also checked that our script downloads data correctly.

@berkaybulut or @michelle-wms - would you mind doing the submission this week? This only needs to be done by one team member.

Thanks!
Kristin

**Comment by arlincherian** [comment]
Follow-up: Florencia has posted a link on slack with the submission guidelines. For reference: https://ubc-mds.slack.com/archives/C24HUNRJL/p1637365467150600 

- You must include the URL of your public project's repository in your milestone 1 submission on Canvas, so we know where to find it.
- Just before you submit the milestone 1, create a release on your project repository on GitHub and name it 0.0.1. Include the URL to this release in your milestone 1 submission on Canvas.

Thanks, team!

**Comment by michelle-wms** [comment]
Yes I can do the submission this week! Sounds good, will review the work. Thanks v much guys!

**Comment by michelle-wms** [comment]
Hi guys, couple of comments before I submit:

1. The requirements said "You are not required upload the data to your project repository." So I am removing all the raw csv files from our repo. I think generally speaking, github repos don't usually store the datasets as common practice as well (since they can get very big).
2. I am making minor edit to the name of the EDA literate document so that it's clearer to the TA which notebook contains our actual EDA (So I will change from coffee_rating.ipynb to coffee_rating_milestone1_EDA_final.ipynb)
3.  For README, introduction: **"Our team chose to analyze the coffee quality data set to identify the strongest predictor of coffee quality. "** --> I am changing to "**Our team will use machine learning techniques to predict coffee quality scores on arabica coffees."** Because "predictor" in machine learning speak means "feature" which is slightly misleading, so it sounded like we're trying to figure out which feature is the best feature. 

Let me know if you've any thoughts - else if ok, please give thumbs up! Thank you.

**Comment by khbunyan** [comment]
Hey @michelle-wms once the milestone is submitted, can you please close out this issue? Thanks! Happy Saturday.

**Comment by michelle-wms** [comment]
Sure will do, I'm coordinating with Berkay to finish up some small stuff!
Should be done by tonight (currently outside now). Thanks!
Happy weekend too

**Comment by michelle-wms** [comment]
Submitted
